const InitialItems = [
  { id: 1, name: "Good Mood", Packed: true },
  { id: 2, name: "Passport", Packed: true },
  { id: 3, name: "Tickets", Packed: false },
  { id: 4, name: "Credit Cards", Packed: true },
  { id: 5, name: "Cash", Packed: false },
  { id: 6, name: "Phone", Packed: true },
  { id: 7, name: "Headphones", Packed: false },
  { id: 8, name: "Charger", Packed: true },
  { id: 9, name: "Power Bank", Packed: false },
  { id: 10, name: "Toothbrush", Packed: true },
  { id: 11, name: "Toothpaste", Packed: false },
  { id: 12, name: "Shampoo", Packed: true },
  { id: 13, name: "Conditioner", Packed: false },
  { id: 14, name: "Shower Gel", Packed: true },
  { id: 15, name: "Towel", Packed: false },
  { id: 16, name: "Underwear", Packed: true },
  { id: 17, name: "Socks", Packed: false },
  { id: 18, name: "T-Shirts", Packed: true },
  { id: 19, name: "Shorts", Packed: false },
  { id: 20, name: "Swimming Suit", Packed: true },
  { id: 21, name: "Sunscreen", Packed: false },
  { id: 22, name: "Hat", Packed: true },
  { id: 23, name: "Sunglasses", Packed: false },
  { id: 24, name: "Book", Packed: true },
  { id: 25, name: "Pen", Packed: false },
  { id: 26, name: "Notebook", Packed: true },
  { id: 27, name: "Medicines", Packed: false },
  { id: 28, name: "First Aid Kit", Packed: true },
]
const secondaryButtons = [
  "Mark all as complete",
  "Mark all as incomplete",
  "Reset To Initial",
  "Remove All Items",
]
export { InitialItems, secondaryButtons }
